/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as TermoDeCienciaRouteImport } from './routes/termo-de-ciencia'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AceiteRouteImport } from './routes/aceite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppSuporteRouteImport } from './routes/app.suporte'
import { Route as AppLouvoresRouteImport } from './routes/app.louvores'
import { Route as AppEbooksRouteImport } from './routes/app.ebooks'
import { Route as AppDevocionaisRouteImport } from './routes/app.devocionais'
import { Route as AppDepoimentosRouteImport } from './routes/app.depoimentos'
import { Route as AdminWebhooksRouteImport } from './routes/admin.webhooks'
import { Route as AdminVendasRouteImport } from './routes/admin.vendas'
import { Route as AdminTrackingRouteImport } from './routes/admin.tracking'
import { Route as AdminSuporteRouteImport } from './routes/admin.suporte'
import { Route as AdminQuizRouteImport } from './routes/admin.quiz'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminMembrosRouteImport } from './routes/admin.membros'
import { Route as AdminLouvoresRouteImport } from './routes/admin.louvores'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminEbooksRouteImport } from './routes/admin.ebooks'
import { Route as AdminCursosRouteImport } from './routes/admin.cursos'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminAudiosRouteImport } from './routes/admin.audios'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAcessosRouteImport } from './routes/admin.acessos'
import { Route as AppVolumeTurnoRouteImport } from './routes/app.volume.$turno'
import { Route as AppSuporteTicketIdRouteImport } from './routes/app.suporte.$ticketId'
import { Route as AppDevocionalSlugRouteImport } from './routes/app.devocional.$slug'
import { Route as ApiPublicWebhooksKirvanoRouteImport } from './routes/api/public/webhooks/kirvano'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const TermoDeCienciaRoute = TermoDeCienciaRouteImport.update({
  id: '/termo-de-ciencia',
  path: '/termo-de-ciencia',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AceiteRoute = AceiteRouteImport.update({
  id: '/aceite',
  path: '/aceite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppLouvoresRoute = AppLouvoresRouteImport.update({
  id: '/louvores',
  path: '/louvores',
  getParentRoute: () => AppRoute,
} as any)
const AppEbooksRoute = AppEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AppRoute,
} as any)
const AppDevocionaisRoute = AppDevocionaisRouteImport.update({
  id: '/devocionais',
  path: '/devocionais',
  getParentRoute: () => AppRoute,
} as any)
const AppDepoimentosRoute = AppDepoimentosRouteImport.update({
  id: '/depoimentos',
  path: '/depoimentos',
  getParentRoute: () => AppRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVendasRoute = AdminVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrackingRoute = AdminTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizRoute = AdminQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembrosRoute = AdminMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLouvoresRoute = AdminLouvoresRouteImport.update({
  id: '/louvores',
  path: '/louvores',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEbooksRoute = AdminEbooksRouteImport.update({
  id: '/ebooks',
  path: '/ebooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCursosRoute = AdminCursosRouteImport.update({
  id: '/cursos',
  path: '/cursos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAudiosRoute = AdminAudiosRouteImport.update({
  id: '/audios',
  path: '/audios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcessosRoute = AdminAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AdminRoute,
} as any)
const AppVolumeTurnoRoute = AppVolumeTurnoRouteImport.update({
  id: '/volume/$turno',
  path: '/volume/$turno',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteTicketIdRoute = AppSuporteTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AppSuporteRoute,
} as any)
const AppDevocionalSlugRoute = AppDevocionalSlugRouteImport.update({
  id: '/devocional/$slug',
  path: '/devocional/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicWebhooksKirvanoRoute =
  ApiPublicWebhooksKirvanoRouteImport.update({
    id: '/api/public/webhooks/kirvano',
    path: '/api/public/webhooks/kirvano',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceite': typeof AceiteRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termo-de-ciencia': typeof TermoDeCienciaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/louvores': typeof AdminLouvoresRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/app/depoimentos': typeof AppDepoimentosRoute
  '/app/devocionais': typeof AppDevocionaisRoute
  '/app/ebooks': typeof AppEbooksRoute
  '/app/louvores': typeof AppLouvoresRoute
  '/app/suporte': typeof AppSuporteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/devocional/$slug': typeof AppDevocionalSlugRoute
  '/app/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/app/volume/$turno': typeof AppVolumeTurnoRoute
  '/api/public/webhooks/kirvano': typeof ApiPublicWebhooksKirvanoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceite': typeof AceiteRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termo-de-ciencia': typeof TermoDeCienciaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/louvores': typeof AdminLouvoresRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/app/depoimentos': typeof AppDepoimentosRoute
  '/app/devocionais': typeof AppDevocionaisRoute
  '/app/ebooks': typeof AppEbooksRoute
  '/app/louvores': typeof AppLouvoresRoute
  '/app/suporte': typeof AppSuporteRouteWithChildren
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/app/devocional/$slug': typeof AppDevocionalSlugRoute
  '/app/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/app/volume/$turno': typeof AppVolumeTurnoRoute
  '/api/public/webhooks/kirvano': typeof ApiPublicWebhooksKirvanoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aceite': typeof AceiteRoute
  '/admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termo-de-ciencia': typeof TermoDeCienciaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/acessos': typeof AdminAcessosRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audios': typeof AdminAudiosRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/cursos': typeof AdminCursosRoute
  '/admin/ebooks': typeof AdminEbooksRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/louvores': typeof AdminLouvoresRoute
  '/admin/membros': typeof AdminMembrosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/quiz': typeof AdminQuizRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tracking': typeof AdminTrackingRoute
  '/admin/vendas': typeof AdminVendasRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/app/depoimentos': typeof AppDepoimentosRoute
  '/app/devocionais': typeof AppDevocionaisRoute
  '/app/ebooks': typeof AppEbooksRoute
  '/app/louvores': typeof AppLouvoresRoute
  '/app/suporte': typeof AppSuporteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/app/devocional/$slug': typeof AppDevocionalSlugRoute
  '/app/suporte/$ticketId': typeof AppSuporteTicketIdRoute
  '/app/volume/$turno': typeof AppVolumeTurnoRoute
  '/api/public/webhooks/kirvano': typeof ApiPublicWebhooksKirvanoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceite'
    | '/admin'
    | '/app'
    | '/login'
    | '/politica-de-privacidade'
    | '/reset-password'
    | '/termo-de-ciencia'
    | '/termos-de-uso'
    | '/admin/acessos'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/cursos'
    | '/admin/ebooks'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/louvores'
    | '/admin/membros'
    | '/admin/produtos'
    | '/admin/quiz'
    | '/admin/suporte'
    | '/admin/tracking'
    | '/admin/vendas'
    | '/admin/webhooks'
    | '/app/depoimentos'
    | '/app/devocionais'
    | '/app/ebooks'
    | '/app/louvores'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/app/devocional/$slug'
    | '/app/suporte/$ticketId'
    | '/app/volume/$turno'
    | '/api/public/webhooks/kirvano'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceite'
    | '/login'
    | '/politica-de-privacidade'
    | '/reset-password'
    | '/termo-de-ciencia'
    | '/termos-de-uso'
    | '/admin/acessos'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/cursos'
    | '/admin/ebooks'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/louvores'
    | '/admin/membros'
    | '/admin/produtos'
    | '/admin/quiz'
    | '/admin/suporte'
    | '/admin/tracking'
    | '/admin/vendas'
    | '/admin/webhooks'
    | '/app/depoimentos'
    | '/app/devocionais'
    | '/app/ebooks'
    | '/app/louvores'
    | '/app/suporte'
    | '/admin'
    | '/app'
    | '/app/devocional/$slug'
    | '/app/suporte/$ticketId'
    | '/app/volume/$turno'
    | '/api/public/webhooks/kirvano'
  id:
    | '__root__'
    | '/'
    | '/aceite'
    | '/admin'
    | '/app'
    | '/login'
    | '/politica-de-privacidade'
    | '/reset-password'
    | '/termo-de-ciencia'
    | '/termos-de-uso'
    | '/admin/acessos'
    | '/admin/analytics'
    | '/admin/audios'
    | '/admin/clientes'
    | '/admin/config'
    | '/admin/cursos'
    | '/admin/ebooks'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/louvores'
    | '/admin/membros'
    | '/admin/produtos'
    | '/admin/quiz'
    | '/admin/suporte'
    | '/admin/tracking'
    | '/admin/vendas'
    | '/admin/webhooks'
    | '/app/depoimentos'
    | '/app/devocionais'
    | '/app/ebooks'
    | '/app/louvores'
    | '/app/suporte'
    | '/admin/'
    | '/app/'
    | '/app/devocional/$slug'
    | '/app/suporte/$ticketId'
    | '/app/volume/$turno'
    | '/api/public/webhooks/kirvano'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceiteRoute: typeof AceiteRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermoDeCienciaRoute: typeof TermoDeCienciaRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ApiPublicWebhooksKirvanoRoute: typeof ApiPublicWebhooksKirvanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termo-de-ciencia': {
      id: '/termo-de-ciencia'
      path: '/termo-de-ciencia'
      fullPath: '/termo-de-ciencia'
      preLoaderRoute: typeof TermoDeCienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceite': {
      id: '/aceite'
      path: '/aceite'
      fullPath: '/aceite'
      preLoaderRoute: typeof AceiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/suporte': {
      id: '/app/suporte'
      path: '/suporte'
      fullPath: '/app/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/louvores': {
      id: '/app/louvores'
      path: '/louvores'
      fullPath: '/app/louvores'
      preLoaderRoute: typeof AppLouvoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ebooks': {
      id: '/app/ebooks'
      path: '/ebooks'
      fullPath: '/app/ebooks'
      preLoaderRoute: typeof AppEbooksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/devocionais': {
      id: '/app/devocionais'
      path: '/devocionais'
      fullPath: '/app/devocionais'
      preLoaderRoute: typeof AppDevocionaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/depoimentos': {
      id: '/app/depoimentos'
      path: '/depoimentos'
      fullPath: '/app/depoimentos'
      preLoaderRoute: typeof AppDepoimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/vendas': {
      id: '/admin/vendas'
      path: '/vendas'
      fullPath: '/admin/vendas'
      preLoaderRoute: typeof AdminVendasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tracking': {
      id: '/admin/tracking'
      path: '/tracking'
      fullPath: '/admin/tracking'
      preLoaderRoute: typeof AdminTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quiz': {
      id: '/admin/quiz'
      path: '/quiz'
      fullPath: '/admin/quiz'
      preLoaderRoute: typeof AdminQuizRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/membros': {
      id: '/admin/membros'
      path: '/membros'
      fullPath: '/admin/membros'
      preLoaderRoute: typeof AdminMembrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/louvores': {
      id: '/admin/louvores'
      path: '/louvores'
      fullPath: '/admin/louvores'
      preLoaderRoute: typeof AdminLouvoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ebooks': {
      id: '/admin/ebooks'
      path: '/ebooks'
      fullPath: '/admin/ebooks'
      preLoaderRoute: typeof AdminEbooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cursos': {
      id: '/admin/cursos'
      path: '/cursos'
      fullPath: '/admin/cursos'
      preLoaderRoute: typeof AdminCursosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audios': {
      id: '/admin/audios'
      path: '/audios'
      fullPath: '/admin/audios'
      preLoaderRoute: typeof AdminAudiosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/acessos': {
      id: '/admin/acessos'
      path: '/acessos'
      fullPath: '/admin/acessos'
      preLoaderRoute: typeof AdminAcessosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/volume/$turno': {
      id: '/app/volume/$turno'
      path: '/volume/$turno'
      fullPath: '/app/volume/$turno'
      preLoaderRoute: typeof AppVolumeTurnoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suporte/$ticketId': {
      id: '/app/suporte/$ticketId'
      path: '/$ticketId'
      fullPath: '/app/suporte/$ticketId'
      preLoaderRoute: typeof AppSuporteTicketIdRouteImport
      parentRoute: typeof AppSuporteRoute
    }
    '/app/devocional/$slug': {
      id: '/app/devocional/$slug'
      path: '/devocional/$slug'
      fullPath: '/app/devocional/$slug'
      preLoaderRoute: typeof AppDevocionalSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/webhooks/kirvano': {
      id: '/api/public/webhooks/kirvano'
      path: '/api/public/webhooks/kirvano'
      fullPath: '/api/public/webhooks/kirvano'
      preLoaderRoute: typeof ApiPublicWebhooksKirvanoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcessosRoute: typeof AdminAcessosRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAudiosRoute: typeof AdminAudiosRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminCursosRoute: typeof AdminCursosRoute
  AdminEbooksRoute: typeof AdminEbooksRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLouvoresRoute: typeof AdminLouvoresRoute
  AdminMembrosRoute: typeof AdminMembrosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminQuizRoute: typeof AdminQuizRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminTrackingRoute: typeof AdminTrackingRoute
  AdminVendasRoute: typeof AdminVendasRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcessosRoute: AdminAcessosRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAudiosRoute: AdminAudiosRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminCursosRoute: AdminCursosRoute,
  AdminEbooksRoute: AdminEbooksRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLouvoresRoute: AdminLouvoresRoute,
  AdminMembrosRoute: AdminMembrosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminQuizRoute: AdminQuizRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminTrackingRoute: AdminTrackingRoute,
  AdminVendasRoute: AdminVendasRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppSuporteRouteChildren {
  AppSuporteTicketIdRoute: typeof AppSuporteTicketIdRoute
}

const AppSuporteRouteChildren: AppSuporteRouteChildren = {
  AppSuporteTicketIdRoute: AppSuporteTicketIdRoute,
}

const AppSuporteRouteWithChildren = AppSuporteRoute._addFileChildren(
  AppSuporteRouteChildren,
)

interface AppRouteChildren {
  AppDepoimentosRoute: typeof AppDepoimentosRoute
  AppDevocionaisRoute: typeof AppDevocionaisRoute
  AppEbooksRoute: typeof AppEbooksRoute
  AppLouvoresRoute: typeof AppLouvoresRoute
  AppSuporteRoute: typeof AppSuporteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppDevocionalSlugRoute: typeof AppDevocionalSlugRoute
  AppVolumeTurnoRoute: typeof AppVolumeTurnoRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDepoimentosRoute: AppDepoimentosRoute,
  AppDevocionaisRoute: AppDevocionaisRoute,
  AppEbooksRoute: AppEbooksRoute,
  AppLouvoresRoute: AppLouvoresRoute,
  AppSuporteRoute: AppSuporteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppDevocionalSlugRoute: AppDevocionalSlugRoute,
  AppVolumeTurnoRoute: AppVolumeTurnoRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceiteRoute: AceiteRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermoDeCienciaRoute: TermoDeCienciaRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ApiPublicWebhooksKirvanoRoute: ApiPublicWebhooksKirvanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
